spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/meddrug
    username: postgres
    password: root
  liquibase:
    change-log: classpath:db/changelog/changelog.xml
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate.ddl-auto: validate
    properties.hibernate.jdbc.lob.non_contextual_creation: true
  session:
    jdbc:
      initialize-schema: always
      table-name: SPRING_SESSION